#My SDL video and gui stuff

#-lSDL -lSDL_ttf -o myemu

_OBJS=.objs/main.o
_CFLAGS=-g -IC:/mingw/include -IC:\MinGW\lib\gcc\mingw32\3.4.5\include -c
default:
	gcc $(_CFLAGS) main.c -o .objs/main.o

	g++ -shared -W1 $(_OBJS) -lSDL -o 86Gui.dll

clean:
	rm $(_OBJS)
