<?php
	include_once 'security.php';
	$theme_version="v0.1";
	//headers..
	if($current_page!="blank.php"){
		$tmp1=array_search($current_page,$add_file_table);
		$current_title=$add_title_table[$tmp1];
	}else{
		$current_title="Test Theme Home";
	}

	echo "<html>\n<head><title>$current_title</title></head>";
	echo "\n\n<!-- This page was generated by the Test Theme($theme_version) of Niche($niche_core_version)-->\n\n";
	echo "<body>\n";
	//navigation
	echo "<b>::Navigation::</b><br><br>\n";
	echo "<a href=\"?page=blank.php\">Home</a><br>";
	for($i=0;$i<count($add_name_table);$i++){
		$tmp1=$add_name_table[$i];
		$tmp_file=$add_file_table[$tmp1];
		$tmp_link=$add_link_table[$tmp1];
		echo "<a href=\"?page=$tmp_file\">$tmp_link ($tmp1)</a><br>\n";
	}
	echo "<br><br><b>::Content::</b><br><br>\n";
	include $current_page;
	echo "\n</body></html>\n";
















?>
